# Generated by Django 4.2.2 on 2023-06-19 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='name',
            new_name='answer',
        ),
        migrations.RemoveField(
            model_name='album',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='album',
        ),
        migrations.AddField(
            model_name='musicgenre',
            name='artist',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musicgenre',
            name='quiz',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='music_genre', to='api.quiz'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='question1',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='question2',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='question3',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
