# Generated by Django 4.2.2 on 2023-06-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_musicgenrequiz_remove_musicgenre_quiz_delete_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicgenrequiz',
            name='question_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
